- name: database
  docker_container:
    name: database
    image: alexishpr/tp1_database:latest
    restart_policy: always
    env:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: db
    volumes:
      - /data

    networks:
      - name: app-network
