language: java

services:
  - docker

script:
  #TODO: test and build your application with maven
  - mvn clean verify --file ./simple-api/pom.xml
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose build
  - docker-compose push
