language: java

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - mvn clean verify --file ./simple-api/pom.xml
        - mvn clean verify --file ./simple-api/pom.xml org.jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Docker-tp2

    - stage: deploy
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker-compose build
        - docker-compose push

cache:
  directories:
    - "HOME/.m2"

addons:
  sonarcloud:
    organization: "alexishpr"
    token: "$SONARCLOUD_TOKEN"
