- name: Create the proxy container
  docker_container:
    name: reverse_proxy
    image: alexishpr/httpd
    pull: true
    restart_policy: always
    ports:
      - "80:80"

    networks:
      - name: app-network
