- name: database
  docker_container:
    name: database
    image: alexishpt/database
    restart_policy: always
    env:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: db
    volumes:
      - /data
    network:
      - name: app-network
