- name: Run backend
  docker_container:
    name: backend
    image: alexishpr/backend
    restart_policy: always
    env:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"

  networks:
    - name: app-network
