- name: Create api container
  docker_container:
    name: backend
    image: alexishpr/backend
    restart_policy: always
    pull: yes
    env:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"

    networks:
      - name: app-network
